version: '3.3'
services:
  db:
    image: tdsql
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: td-container
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3306:3306'
