version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: mysql-container-2
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
        - '3306:3306'
    volumes:
        - container-volume:/var/lib/mysql
        - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

volumes:
  container-volume: